spring:
  application:
    name: text-corrector-api

  jpa:
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver

  liquibase:
    default-schema: app

server:
  port: 8020

speller:
  url: https://speller.yandex.net/services/spellservice.json
  method-path: /checkTexts
  connect-timeout: 2s
  read-timeout: 5s