spring:
  application:
    name: text-corrector-api
  lifecycle:
    timeout-per-shutdown-phase: 20s

  jpa:
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver

  liquibase:
    default-schema: app

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%X{taskId}] - %msg%n"

speller:
  url: https://speller.yandex.net/services/spellservice.json
  method-path: /checkTexts
  connect-timeout: 2s
  read-timeout: 5s
  text-limit: 10000

scheduler:
  delay: 5000
  batch-size: 10